name: online_shopping
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^3.26.0
  flutter_sms: ^2.1.1
  google_sign_in: ^4.5.6
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"
  flutter_facebook_auth: "^1.0.0"
  flutter_facebook_login: ^3.0.0
  keyboard_dismisser: ^1.0.2
  sqflite: ^1.3.0
  path: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true




